direction: right

Individuals --> Reduce, Reuse, Recycle
Individuals --> Plant Trees
Individuals --> Switch to Renewable Energy
Individuals --> Eat Less Meat
Individuals --> Use Public Transportation

Communities --> Reduce, Reuse, Recycle
Communities --> Plant Trees
Communities --> Switch to Renewable Energy

Governments --> Government Policies